const RESPONSE_CODES = {
  SUCCESS: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UN_AUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNSUPPORTED_MEDIATYPE: 415,
  EXPECTATION_FAILED: 417,
  UN_PROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
};

const CONFIG = {
  JWT_SECRET_KEY:
    process.env.JWT_SECRET_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9",
  BCRYPT_SALT_ROUNDS: 10,
  AWS_S3_BUCKET_NAME: process.env.AWS_S3_BUCKET_NAME || "storify-bucket",
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID || "",
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY || "",
  AWS_S3_BUCKET_REGION: process.env.AWS_S3_BUCKET_REGION || "ap-south-1",
};

module.exports = {
  RESPONSE_CODES,
  CONFIG,
};
